### ISSUE TITLE
Extract files to Windows Host

### ISSUE THREAD

**Issue by f135ta** [srwareham/dffmpeg#2]
Hi, i'm using this to process videos from an http source (HLS).. It generates the files and I can see them inside the container. 

However, I'm hosting it in a Windows Host, and need to be able to extract the files out to a folder on the host.

Is this possible please?

**Comment by srwareham** [comment]
By what means are you hosting this on Windows? I'd suggest using WSL 2 if you're not already: https://docs.docker.com/docker-for-windows/wsl/

Basically you get a full linux subsystem on your Windows machine. The installation will have a home directory accessible via Windows explorer (usually `\\wsl$\NAME_OF_LINUX_DISTRO`)
