### ISSUE TITLE
Confused n00b

### ISSUE THREAD

**Issue by neo-neo1** [srwareham/dffmpeg#3]
As a confused Docker n00b I'm running a container from LinuxServer.io. However, the image is missing a crucial plugin that I need (ffmpeg), is this project an advisable fix? All I want to do is add ffmpeg to a preexisting LinuxServer.io image and not have to do redo adding ffmpeg when I pull new images for updates. Any outline of steps to achieve this?

Sorry for the basic question, thanks for your patience.

**Comment by srwareham** [comment]
The goal of this project is to allow your host system to use ffmpeg without having to natively install it. It sounds like on the other hand you just want to install ffmpeg within a specific container. If you don't have any weird codec requirements it's probably as simple as adding `apt-get install ffmpeg ` to whatever dockerfile you're using. Shouldn't add much time at all when updating.
